#!/bin/sh
INT=eth0

iptables -F
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

#
#iptables -A OUTPUT -o $INT -p udp --dport 500 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
#iptables -A INPUT -i $INT -p udp --sport 500 -m conntrack --ctstate ESTABLISHED -j ACCEPT

#iptables -A OUTPUT -o $INT  -p udp --dport 4500 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
#iptables -A INPUT -i $INT -p udp --sport 4500 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

# outgoing DNS
iptables -A OUTPUT -o $INT -p udp --dport 53 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p udp --sport 53 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $INT -p tcp --dport 53 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 53 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing NTP
iptables -A OUTPUT -o $INT -p udp --dport 123 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p udp --sport 123 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# whois
#iptables -A OUTPUT -o $INT -p tcp --dport 43 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
#iptables -A INPUT -i $INT -p tcp --sport 43 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing ICMP
iptables -A OUTPUT -o $INT -p icmp -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p icmp -m conntrack --ctstate ESTABLISHED -j ACCEPT

# openvpn
iptables -A OUTPUT -o eth0 -p udp --dport 1194 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i eth0 -p udp --sport 1194 -m conntrack --ctstate ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o tun0 -p udp --dport 1194 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i tun0 -p udp --sport 1194 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing ssh
iptables -A OUTPUT -o $INT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o $INT -p tcp --dport 9418 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 9418 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# dhcp
iptables -A OUTPUT -o $INT -p udp --dport 67 --sport 68 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p udp --sport 67 --dport 68 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing HTTP
iptables -A OUTPUT -o $INT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 80 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing HTTPS
iptables -A OUTPUT -o $INT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# gpg
iptables -A OUTPUT -o $INT -p tcp --dport 11371 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 11371 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing POP
iptables -A OUTPUT -o $INT -p tcp --dport 110 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 110 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# outgoing SMTP
iptables -A OUTPUT -o $INT -p tcp --dport 587 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 587 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o $INT -p tcp --dport 993 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 993 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o $INT -p tcp --dport 465 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A INPUT -i $INT -p tcp --sport 465 -m conntrack --ctstate ESTABLISHED -j ACCEPT

iptables -A OUTPUT -o $INT -p udp --dport 4500 -j ACCEPT
iptables -A INPUT -i $INT -p udp --sport 4500 -j ACCEPT
iptables -A OUTPUT -o $INT -p udp --dport 500 -j ACCEPT
iptables -A INPUT -i $INT -p udp --sport 500 -j ACCEPT

# log dropped connections
iptables -A INPUT -j LOG --log-prefix "IN-DROPPED "
iptables -A OUTPUT -j LOG --log-prefix "OUT-DROPPED "


